/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiApprovalsRouteImport } from './routes/api.approvals'
import { Route as ApiCancelRouteImport } from './routes/api.cancel'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiEventsRouteImport } from './routes/api.events'
import { Route as ApiThreadsRouteImport } from './routes/api.threads'
import { Route as ApiTranscriptRouteImport } from './routes/api.transcript'
import { Route as AppTThreadIdRouteImport } from './routes/_app/t/$threadId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiApprovalsRoute = ApiApprovalsRouteImport.update({
  id: '/api/approvals',
  path: '/api/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCancelRoute = ApiCancelRouteImport.update({
  id: '/api/cancel',
  path: '/api/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreadsRoute = ApiThreadsRouteImport.update({
  id: '/api/threads',
  path: '/api/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscriptRoute = ApiTranscriptRouteImport.update({
  id: '/api/transcript',
  path: '/api/transcript',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTThreadIdRoute = AppTThreadIdRouteImport.update({
  id: '/t/$threadId',
  path: '/t/$threadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/api/approvals': typeof ApiApprovalsRoute
  '/api/cancel': typeof ApiCancelRoute
  '/api/chat': typeof ApiChatRoute
  '/api/events': typeof ApiEventsRoute
  '/api/threads': typeof ApiThreadsRoute
  '/api/transcript': typeof ApiTranscriptRoute
  '/t/$threadId': typeof AppTThreadIdRoute
}
export interface FileRoutesByTo {
  '/api/approvals': typeof ApiApprovalsRoute
  '/api/cancel': typeof ApiCancelRoute
  '/api/chat': typeof ApiChatRoute
  '/api/events': typeof ApiEventsRoute
  '/api/threads': typeof ApiThreadsRoute
  '/api/transcript': typeof ApiTranscriptRoute
  '/': typeof AppIndexRoute
  '/t/$threadId': typeof AppTThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/api/approvals': typeof ApiApprovalsRoute
  '/api/cancel': typeof ApiCancelRoute
  '/api/chat': typeof ApiChatRoute
  '/api/events': typeof ApiEventsRoute
  '/api/threads': typeof ApiThreadsRoute
  '/api/transcript': typeof ApiTranscriptRoute
  '/_app/': typeof AppIndexRoute
  '/_app/t/$threadId': typeof AppTThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/approvals'
    | '/api/cancel'
    | '/api/chat'
    | '/api/events'
    | '/api/threads'
    | '/api/transcript'
    | '/t/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/approvals'
    | '/api/cancel'
    | '/api/chat'
    | '/api/events'
    | '/api/threads'
    | '/api/transcript'
    | '/'
    | '/t/$threadId'
  id:
    | '__root__'
    | '/_app'
    | '/api/approvals'
    | '/api/cancel'
    | '/api/chat'
    | '/api/events'
    | '/api/threads'
    | '/api/transcript'
    | '/_app/'
    | '/_app/t/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiApprovalsRoute: typeof ApiApprovalsRoute
  ApiCancelRoute: typeof ApiCancelRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiThreadsRoute: typeof ApiThreadsRoute
  ApiTranscriptRoute: typeof ApiTranscriptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/approvals': {
      id: '/api/approvals'
      path: '/api/approvals'
      fullPath: '/api/approvals'
      preLoaderRoute: typeof ApiApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cancel': {
      id: '/api/cancel'
      path: '/api/cancel'
      fullPath: '/api/cancel'
      preLoaderRoute: typeof ApiCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/threads': {
      id: '/api/threads'
      path: '/api/threads'
      fullPath: '/api/threads'
      preLoaderRoute: typeof ApiThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcript': {
      id: '/api/transcript'
      path: '/api/transcript'
      fullPath: '/api/transcript'
      preLoaderRoute: typeof ApiTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/t/$threadId': {
      id: '/_app/t/$threadId'
      path: '/t/$threadId'
      fullPath: '/t/$threadId'
      preLoaderRoute: typeof AppTThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppTThreadIdRoute: typeof AppTThreadIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppTThreadIdRoute: AppTThreadIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiApprovalsRoute: ApiApprovalsRoute,
  ApiCancelRoute: ApiCancelRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiThreadsRoute: ApiThreadsRoute,
  ApiTranscriptRoute: ApiTranscriptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
